### ISSUE TITLE
mvn profiles doesn´t work

### ISSUE THREAD

**Issue by evleite** [selakavon/spring-rest-oauth2-mongo#1]
Hi there,

first of all, thanks for share this amazing projet.

I was trying to run this project using the command mvn spring-boot:run -Drun.profiles=https,localmongo, but got maven phase problems:
[ERROR] Unknown lifecycle phase ".profiles=https,localmongo".

And I was checking the code there are no references to application-https.properties, so how should I start with https ?

best regards,

Eduardo.

**Comment by selakavon** [comment]
Hi Eduardo,
  thanks for visiting my repository, it's great to see this project may be helping somebody.

Is it possible you have a typo in your command?

This response is mavens way to say he considers .profiles=... to be a goal (like clean, install ...). It suggests .profile= is taken as a command argument and therefore follows space or tab.

I have tried i.e. mvn spring-boot:run -Drun[space].profiles=https,localmongo (replace [space] with space character) and received the same response. 

For mvn spring-boot:run -Drun .profiles=https,localmongo it seems to be working fine for me.

application-https.properties file is probably defined somewhere in spring boot plugin itself by default and triggered by maven profile.

Please let me now it if helped.

Thank you,
Ales

**Comment by evleite** [comment]
Hi Ales,

thanks for your quick response.

I have tried the way you suggested before, but got the same problem:
[image: pasted1]
I am using maven 3, I do not know ig there are some relation with, I
believe not.

first I ran mvn clean install and works fine, after that I have tried the
command mvn spring-boot:run -Drun .profiles=https,localmongo but did not
work.

I did not see on pom file https and localmongo profiles, do you think this
can be the root cause?

Best Regards,

Eduardo.

Em sex, 16 de set de 2016 às 08:35, Ales Novak notifications@github.com
escreveu:

**Comment by evleite** [comment]
Hi Ales,

I have tried like this and works fine. mvn spring-boot:run -D[space]run.profiles=https,localmongo

Thank you very much for you attention.

Best regards,

Eduardo
