### ISSUE TITLE
All your CURL commands doesn't works

### ISSUE THREAD

**Issue by ghost** [selakavon/spring-rest-oauth2-mongo#2]
Not sure why CURL command doesn't works ? If I execute the using browser then it works, but not sure why 

curl -X GET https://localhost:8443/api -k doesn't works ? 

`C:\>curl -X GET https://localhost:8443/api -k
curl: (7) Failed to connect to localhost port 8443: Connection refused`

**Comment by selakavon** [comment]
I've tried to reproduce your problem.

Compile and start the server:
mvn clean install
mvn spring-boot:run -Drun.profiles=https 

Query:
curl -X GET https://localhost:8443/api -k
Response:
{"_links":{"users":{"href":"https://localhost:8443/api/users"}}}

What does the spring boot server log say?
I guess telnet localhost 8443 tells you "Connection refused", doesn't it?

**Comment by ghost** [comment]
Yes, you're right. Also I have added latest JCE files for Java 8 into the security/lib folder. How we can fixed this issue ? 
Nothing is showing on the logs:

![image](https://user-images.githubusercontent.com/8208031/30276878-dbdd80f4-9723-11e7-83dd-d91188d09002.png)


![image](https://user-images.githubusercontent.com/8208031/30276909-f442e530-9723-11e7-809d-36baa44f8466.png)

**Comment by selakavon** [comment]
If you are able to connect by browser and not curl, then it's not a problem of the application.
It's possible that curl is different on windows and linux ... Try different (GUI) client.
