### ISSUE TITLE
Unable to create the user

### ISSUE THREAD

**Issue by ghost** [selakavon/spring-rest-oauth2-mongo#4]
I am getting the below error while executing the below CURL:
```
C:\>curl -X POST https://localhost:8443/api/users -k -d '{"fullName":"Ales Novak","userName":"ales","password":"secret"}' -H 'Content-Type: application/json'
{"timestamp":1505151985452,"status":415,"error":"Unsupported Media Type","exception":"org.springframework.web.HttpMediaTypeNotSupportedException","message":"Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported","path":"/api/users"}

curl: (6) Could not resolve host: application
```

**Comment by selakavon** [comment]
"Could not resolve host: application" and "Unsupported Media Type" means that curl recognize application/json as a hostname parameter. So the command interpretter parses your command in a wrong way.
Try to run it in cygwin or use another client like postman.

**Comment by ghost** [comment]
Hey I am getting the same issue with Postman, RESTClient etc. I used this using GIT command line, but still issue is same
Please guide.
